--liquibase formatted sql

--changeset author:rdube26:insert_ira_prod_type
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('ACCERTIFY ', 'Accertify                     ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('ACH-WIRE  ', 'ACH/Wire Transfer Processing  ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('ATM-OPER  ', 'ATM Operational Partners      ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('ATM-TECH  ', 'ATM Technical Partners        ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('BANK-BLEND', 'Business Lending/Credit Prds  ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('BANK-BREST', 'Business Restrctd Lending Prds');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('BANK-BSAV ', 'Business Savings/Deposit Prds ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('BANK-BSPEC', 'Business Special/Other Prds   ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('BANK-BTERM', 'Business Certificate/Term Prds');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('BANK-PAYM ', 'BIP services for BANK         ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('BANK-PBCK ', 'Payback Business Partners     ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('BANK-PLEND', 'Personal Lending/Credit Prds  ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('BANK-PREST', 'Personal Restrctd Lending Prds');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('BANK-PSAV ', 'Personal Savings/Deposit Prds ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('BANK-PTERM', 'Personal Certificate/Term Prds');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('BRK-DEP   ', 'Brokered Deposit Products     ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('CFX       ', 'Corporate Foreign Exchange    ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('CHEQUE    ', 'Cheque Products               ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('CONS-CHRG ', 'Consumer Charge Card Products ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('CONS-CRED ', 'Consumer Credit Card Products ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('CONS-NBL  ', 'Consumer Credit Products      ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('CORP-BTA  ', 'Business Travel Acct Products ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('CORP-CARD ', 'Corporate Charge Card Products');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('CORP-CPC  ', 'Corp Purch Card Products      ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('CORP-CTRL ', 'Global Corporate Ctrl Accounts');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('CORP-LGT  ', 'Global Corporate LE Accounts  ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('CORP-PAYM ', 'Corporate Payments            ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('CORP-PURC ', 'Corp Purch Card-less Products ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('CORP-VPAY ', 'V-Payment Products            ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('FOR-CORR  ', 'Foreign Correspondent Accounts');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('FXIP-BUS  ', 'F/X Intl Payment Services     ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('FXIP-FI   ', 'F/X Intl Paymnts for Fin Insts');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('FXIP-GOV  ', 'F/X Intl Paymnts for Governmnt');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('FXIP-IND  ', 'F/X Intl Paymnts for Individls');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('GMS-AP    ', 'Acquisition Participants      ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('GMS-ASP   ', 'Acquiring Service Providers   ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('GNS-PARTN ', 'Global Network Partners       ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('ICC-PARTN ', 'ICC Business Banking Partner  ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('INNON-SELL', 'InComm Non-Sellers            ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('INS-BUSN  ', 'Business Insurance Prds (Fee) ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('INS-PERS  ', 'Personal Insurance Prds (Fee) ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('INSELL-RP ', 'InComm Plastic Seller-Restrctd');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('INSELL-UP ', 'Incomm Plastic Sellers Unrestr');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('KYS-ACM   ', 'Know your seller - ACM        ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('KYS-PUR   ', 'Know your seller - Purchaser  ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('LOY-EDGE  ', 'LoyaltyEdge                   ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('LOY-PART  ', 'Loyalty Programs (LP / Plenti)');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('NON-SELL  ', 'Non-Sellers                   ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('OTHER-RETL', 'Other Retail Services         ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('PAYVE     ', 'PAYVE                         ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('PCS-PARTN ', 'Partner Card Services Partners');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('RELO-BUS  ', 'Business Re-loadable Prepaids ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('RELO-PER  ', 'Personal Re-loadable Prepaids ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('RFX       ', 'Foreign Exchange Services     ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('SBS-CHRG  ', 'OPEN/SBS Charge Card Products ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('SBS-CRED  ', 'OPEN/SBS Credit Card Products ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('SBS-NBL   ', 'Business Credit Products      ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('BANK-PCA  ', 'Personal Checking Accounts    ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('SE-DIR    ', 'Merchants (Direct SEs)        ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('SE-OPT    ', 'OptBlue Merchants             ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('SELL-RP   ', 'Plastic Sellers (Restricted)  ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('SELL-TC   ', 'Paper Sellers                 ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('SELL-UP   ', 'Plastic Sellers (Unrestricted)');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('SING-BUS  ', 'Business Single Load Prepaids ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('SING-PER  ', 'Personal Single Load Prepaids ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('TRAV-BUSN ', 'Business Travel Services      ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('TRAV-CONS ', 'Consumer Travel               ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('TRAV-MEET ', 'Business Trvl-Meeting & Events');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('WCS-BANK  ', 'Whls Curr Srvs for Banks      ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('WCS-GOV   ', 'Whls Curr Servs for Government');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('WCS-NBFI  ', 'Whls Curr Srvs for Non-Banks  ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('CONS-P2P  ', 'P2P Service for Consumer      ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('SE-KAB    ', 'Kabbage Merchants             ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('PAY-B2B   ', 'Global Pay Services - Business');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('BANK-BCA  ', 'Business Checking Accounts    ');
INSERT INTO ira_prod_type (ira_prod_type_cd, prod_type_nm) VALUES ('CONS-CPA  ', 'CRYPTO services for consumer  ');
