--liquibase formatted sql

--changeset author:rdube26:insert_ira_indus_type
INSERT INTO ira_indus_type (ira_indus_type_cd, indus_type_nm)
VALUES ('AERO-DEF', 'Aerospace & Defense'),
       ('AGRI-HUNT', 'Agriculture, Forestry, Fishing, Hunting'),
       ('AIR-COND', 'Steam & Air-Conditioning Supply'),
       ('AIR-TRANS', 'Air Carrier & Air Passenger Transportation'),
       ('ANTIQUES', 'Antique & Art dealers'),
       ('ART-ENT', 'Arts, Entertainment, and Recreation'),
       ('ART-ENTCSH', 'Arts, Entertainment, and Recreation (Cash Intensive)'),
       ('AUTO-DLR', 'Automobile/ Motor Vehicle/ Truck Dealerships'),
       ('AUTO-SERV', 'Automobile/ Motor Vehicle/ Truck Machine Part Manufacturers; Repair and Services (New & Used)'),
       ('BANK-COM', 'Commercial Banks'),
       ('BANK-DEP', 'Banks, Deposit Brokers and Depositories'),
       ('BT-PL-DLR', 'Boat and Plane Dealerships'),
       ('BT-PL-MFR', 'Boat and Plane Manufacturers'),
       ('BT-PL-SERV', 'Boat and Plane Repair and Services (New & Used)'),
       ('CALL-CARDS', 'Calling Cards'),
       ('CASINOS', 'Casinos, Card Clubs, Gambling Locations & Gaming Establishments'),
       ('CAST-MTLS', 'Casting'),
       ('CHARITY', 'Charities (including unregulated charities) & Religious Organizations'),
       ('CIG-DIST', 'Cigarette Distribution'),
       ('CIGS-LIQR', 'Retail of Food, Beverage, Liquor and Cigarette & Tobacco Distribution'),
       ('COMPUTER', 'Electronics / Computers (including all services)'),
       ('CONSTRUCT', 'Construction, Construction Services (& Materials) and Engineering'),
       ('CONV-STORS', 'Convenience Stores'),
       ('EDU-SERV', 'Education and Education Services'),
       ('ESCORT-MSG', 'Escort services and massage parlors'),
       ('FIN-COL', 'Financial entities (including money transmitters, check cashing facilities, collection agencies)'),
       ('FIN-STOCK',
        'Finance Companies (Trusts, Funds, Insurance Companies, Real Estate, Trading, Stock Exchanges and Services)'),
       ('FLM-TV-PRT', 'Media (Film,Television,Print,D'),
       ('FOOD-PROC', 'Food Processing'),
       ('FREIGHT', 'Freight Transportation (Air, Road, Water)'),
       ('GOV-PUB-AD', 'Government & Public Administration'),
       ('GROC-STORS', 'Grocery Stores'),
       ('GUNS-AMMO', 'Ammunition & Gun Dealers'),
       ('HAIR-BEAUT', 'Hairdresser and Beauty Treatment'),
       ('HEALTH-MED', 'Health Care, Hospitals and Social Assistance'),
       ('HOTEL', 'Lodging / Hotels'),
       ('HOTEL-CSH', 'Lodging / Hotels (Cash Intensive)'),
       ('HOUSE-EMP', 'Household Employer (Cash Intensive)'),
       ('IMP-EXP', 'Import/ export companies'),
       ('INT-ADULT', 'Internet adult digital-content sites and providers (Adult Entertainment)'),
       ('INT-SHOP', 'Internet Shopping'),
       ('JEWL-LTHR', 'Jewelry, Luggage, and Leather Goods Stores'),
       ('LANDSCAPE', 'Landscape Services'),
       ('LTHR-REPR', 'Footwear and Leather Goods Repair'),
       ('MAIL-DLVRY', 'Post Offices, Courier and Express Delivery Activities'),
       ('MARIJ-CANB', 'Marijuana & Cannabis industry'),
       ('MFR', 'Manufacturing'),
       ('MFR-CSH', 'Manufacturing (Cash Intensive)'),
       ('MINING', 'Mining, Quarrying, Oil/ Gas Extraction & Related Industry Activities'),
       ('MISC-REPR', 'Repair Shops & Miscellaneous Repair Services'),
       ('MISC-STORS', 'Misc Store retailers'),
       ('MON-SERV',
        'Money Services Businesses (such as remittance businesses, exchange houses, casa de cambios, and money transfer agents)'),
       ('NON-CLASS', 'Nonclassifiable Establishments'),
       ('NON-PROFIT', 'Non-Profit/ Professional Org/ Civic Org/ Social Org'),
       ('OFFSHORE', 'Offshore corporations and bank located in tax and/ or secrecy havens'),
       ('OTHER-CSH', 'Other Cash Businesses'),
       ('PARK-GRGE', 'Parking Garages'),
       ('PAWN', 'Pawn Brokers'),
       ('PIPELINES', 'Pipe Lines (No Natural Gas)'),
       ('POLITICAL', 'Political Organization'),
       ('PREC-GOODS', 'Dealers in high value or precious goods (such as jewel, gem, and precious metal dealers)'),
       ('PRIV-ATM', 'Privately Owned Automated Teller Machines'),
       ('PROF-SERV', 'Professional service providers (lawyers, accountants, investment brokers)'),
       ('REAL-EST', 'Real Estate Businesses'),
       ('RENT-ACCOM', 'Renting & Leasing'),
       ('RENT-GOODS', 'Renting & Leasing of Consumer Goods, Personal Goods, Recreational Goods and Video, Machinery'),
       ('RENT-VEHCL', 'Renting & Leasing of Motor Vehicles, Boats and Motorized Vehicles'),
       ('RESTAURANT', 'Restaurants / Food Services and Bars'),
       ('RETL-GEN', 'Retail Non-Specialized Stores'),
       ('RETL-MAIL', 'Retail: Mail Order'),
       ('RETL-OTHER',
        'Retail: Automotive, Books, Clothing, Food, Fuel, Gas, Health, Hobbies, Home Goods, Music, Sports and Nonstore Retail'),
       ('RETL-SPEC', 'Retail Specialized Stores'),
       ('RETL-TRADE', 'Retail Trade'),
       ('SERV', 'Services'),
       ('SERV-CLEAN', 'Services: Personal (Washing, Cleaning Services and Dry Cleaning)'),
       ('SERV-CSH', 'Services (Cash Intensive)'),
       ('SERV-RECR', 'Services-Amusement, Recreation Services & Membership Sports & Recreation Clubs'),
       ('SOCCER', 'Football (Soccer) Clubs, professional sport teams'),
       ('STORAGE', 'Warehousing and Storage'),
       ('TAXI-LIMO', 'Taxi Service & Limousine'),
       ('TECHNOLOGY', 'Technology'),
       ('TELECOM', 'Telecommunications'),
       ('TELEMARKET', 'Telemarketers, Door to Door Sales, Canvasser'),
       ('TELGRPH', 'Telegraph, Telegram and Telephone Services'),
       ('THRIFT-STR', 'Thrift Institutions'),
       ('TRAN-SERV', 'Transportation Services'),
       ('TRAV-AGENT', 'Travel Agencies & Services; Tour Operators'),
       ('TRAVEL-OP', 'Ship, bus and plane operators'),
       ('TRUST', 'Trust Companies'),
       ('UNKNOWN', 'Unknown'),
       ('UTILITIES', 'Public Utilities & Utilities'),
       ('VIDEO-ARC', 'Video Game Arcades'),
       ('WASTE-MGNT', 'Waste Management & Sanitary Services'),
       ('WATER-TRAN',
        'Water Transportation & Water Passenger Transportation (Including fishing boats, ferries, sightseeing and excursions)'),
       ('WHLS-CSH', 'Wholesale Trade (Cash Intensive)'),
       ('WHLS-FOOD', 'Wholesale Food and Beverage Distribution; Consumer Goods, Medical, Pharmaceutical Goods'),
       ('WHLS-TRADE', 'Wholesale Trade');
